### ISSUE TITLE
If the session has the maximum duration disabled, and the profile wants to override the duration, it will fail 

### ISSUE THREAD

**Issue by JennaWbbb** [l0g-0ut/elg#4]
Lets's say you have a profile set to overrideMaximumTime, like
http://localhost:4200/?p=eyJzZXR0aW5nc1Nob3duIjpmYWxzZSwicHJvZmlsZU5hbWUiOiJvaCBkZWFyIiwic2V0dGluZ3MiOnsiaXRlcmF0aW9ucyI6eyJmaXgiOm51bGwsIm1pbiI6MSwibWF4IjoxNTB9LCJwZW5hbHR5Ijp7InRpbWUiOnsiZW5hYmxlZCI6dHJ1ZSwibWluIjo2MCwibWF4IjozMDB9LCJtaW5pbXVtVGltZSI6eyJlbmFibGVkIjpmYWxzZSwibWluIjoxLCJtYXgiOjM2MDB9LCJyZXF1aXJlbWVudHMiOnsiZW5hYmxlZCI6ZmFsc2UsIm1pbiI6MSwibWF4Ijo1fX0sInNsZWVwcyI6eyJtaW4iOjEwLCJtYXgiOjYwfSwiaW5GZWVsaW5nTHVjeSI6ZmFsc2UsIm92ZXJyaWRlTWF4aW11bVRpbWUiOnRydWV9fQ%3D%3D

If you use the API key of a user that has the Maxmimum Duration "disabled", then when coming to this.emlalockService.addMaximumTime, the remote API returns a 400 error, and stops the elg game from continuing

**Comment by l0g-0ut** [comment]
@JennaWbbb: Thank you for that, I'll take care of it.

**Comment by l0g-0ut** [comment]
Solution available with v4.1.1, deployed on 2022-09-19.
